#!/bin/bash
# Run GOTM using with idealized forcing and initial conditions
#
# Brandon Reichl

#######################################################################
#                              Set paths                              #
#######################################################################

# setup paths and tools
source "../../set_tools.sh"

# directory of base case
basecase="${GOTMWORK_ROOT}/data/Idealized"

# current path
curdir=$(pwd)

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="Idealized"

# set levels, grid zooming at surface
nlev=150
depth=165
ddu=0
ddl=0

# set Coriolis
# set Heat Flux
# set Wind Stress
Latitude=45
#MC97
taux=0.037
tauy=0.00
const_u10=10.00
const_v10=0.00
heatflux=-10

# run parameters
dt=60
nsave=60

# starting and ending date - in the format of YYYYMMDD
datestart="20000101"
dateend="20000111"

# name of the turbulence model
# turbmethod="KPPLT-EFACTOR"
# turbmethod="KPPLT-ENTR"
# turbmethod="KPPLT-RWHGK"
# turbmethod="EPBL"
# turbmethod="EPBL-LT"
# turbmethod="KPP-CVMix"
# turbmethod="SMC"
# turbmethod="SMC-KC04"
# turbmethod="SMC-C01A"
 turbmethod="SMC-C01A-lt"
# turbmethod="SMC-C01A-iw"
# turbmethod="SMC-C01A-ibe"
# turbmethod="SMC-C01A-ibf"
# turbmethod="SMC-C01A-lt-iw"
# turbmethod="SMC-C01A-lt-ibe"
# turbmethod="SMC-C01A-lt-ibf"
# turbmethod="SMCLT"
# turbmethod="SMC-YU18"
# turbmethod="SMCOP_7"
# turbmethod="SMCOP-lt"

# output file name
outname="gotm_out"

# case name
casename="${title}_${turbmethod}_${datestart}-${dateend}"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${GOTMRUN_ROOT}/Idealized_Tests/LF17/B/${casename}"
mkdir -p ${rundir}
cd ${rundir}


# copy base case
cp ${basecase}/* ./

# set run parameters
start_time="${datestart:0:4}-${datestart:4:2}-${datestart:6:2} 00:00:00"
stop_time="${dateend:0:4}-${dateend:4:2}-${dateend:6:2} 00:00:00"
${cmd_nmlchange} -f gotmrun.nml -e start -v "${start_time}"
${cmd_nmlchange} -f gotmrun.nml -e stop -v "${stop_time}"
${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
${cmd_nmlchange} -f gotmrun.nml -e dt -v ${dt}
${cmd_nmlchange} -f gotmrun.nml -e nsave -v ${nsave}
${cmd_nmlchange} -f gotmrun.nml -e nlev -v ${nlev}
${cmd_nmlchange} -f gotmrun.nml -e depth -v ${depth}
${cmd_nmlchange} -f gotmrun.nml -e latitude -v ${Latitude}
${cmd_nmlchange} -f gotmmean.nml -e ddu -v ${ddu}
${cmd_nmlchange} -f gotmmean.nml -e ddl -v ${ddl}
${cmd_nmlchange} -f airsea.nml -e const_tx -v ${taux}
${cmd_nmlchange} -f airsea.nml -e const_ty -v ${tauy}
${cmd_nmlchange} -f airsea.nml -e const_heat -v ${heatflux}

${cmd_nmlchange} -f airsea.nml -e const_u10 -v ${const_u10}
${cmd_nmlchange} -f airsea.nml -e const_v10 -v ${const_v10}
${cmd_nmlchange} -f obs.nml -e s_prof_file -v 'sprof_file_MC97.dat'
${cmd_nmlchange} -f obs.nml -e t_prof_file -v 'tprof_file_MC97.dat'

#${cmd_nmlchange} -f gotmmean.nml -e piw_production -v ${piw_production}
#${cmd_nmlchange} -f airsea.nml -e heat_method -v 0
#${cmd_nmlchange} -f airsea.nml -e swr_method -v 0
#${cmd_nmlchange} -f airsea.nml -e momentum_method -v 0
#${cmd_nmlchange} -f gotmrun.nml -e eq_state_method -v 3

#${cmd_nmlchange} -f obs.nml -e ustokes_method -v 7
#${cmd_nmlchange} -f obs.nml -e wave_age -v 0.6
#${cmd_nmlchange} -f obs.nml -e wave_age -v 0.8
#${cmd_nmlchange} -f obs.nml -e wave_age -v 1.0
#${cmd_nmlchange} -f obs.nml -e wave_age -v 1.2

# set turbulence method
source ${scpt_case_turbmethod}

#######################################################################
#                              Run GOTM                               #
#######################################################################
${cmd_gotm} 2> log.${outname}

#######################################################################
#                           Postprocessing                            #
#######################################################################

# plot surface forcing and profiles
source ${curdir}/case_postproc.sh
